/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodeburro;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import lib.*;

/**
 *
 * @author Helison
 */
public class JogoBurro extends javax.swing.JFrame {

    Baralho baralho;
    Jogador jogador1;
    Jogador jogador2;
    JogoDeBurro jogo;
    DefaultComboBoxModel model1;
    DefaultComboBoxModel model2;

    /**
     * Construtor do Jogo de Burro
     */
    public JogoBurro() {
        initComponents();

    }

    /**
     * Metodo que retorna um arraylist contendo as cartas na mao do jogador 1
     * @return
     */
    private String[] carregarCartasMaoJogador1() {
        String[] maoJogador1 = new String[jogador1.maoJogador.size()];
        for (int i = 0; i < jogador1.maoJogador.size(); i++) {
            String concat = jogador1.maoJogador.get(i).getNumero() + " " + jogador1.maoJogador.get(i).getnaipe();
            maoJogador1[i] = concat;
        }
        return maoJogador1;

    }
    /**
     * Metodo que retorna um arraylist contendo as cartas na mao do jogador 2
     * @return
     */
    private String[] carregarCartasMaoJogador2() {
        String[] maoJogador1 = new String[jogador2.maoJogador.size()];
        for (int i = 0; i < jogador2.maoJogador.size(); i++) {
            String concat = jogador2.maoJogador.get(i).getNumero() + " " + jogador2.maoJogador.get(i).getnaipe();
            maoJogador1[i] = concat;
        }
        return maoJogador1;

    }
    /**
     * Metodo que atualiza os dados do combobox do jogador1
     */

    private void atualizaComboboxJogador1() {
        model1 = new DefaultComboBoxModel(carregarCartasMaoJogador1());
        jComboBoxP1.removeAllItems();
        jComboBoxP1.setModel(model1);
        //jComboBoxP2.setModel(new javax.swing.DefaultComboBoxModel(this.carregarCartasMaoJogador1()));
    }
    /**
     * Metodo que atualiza os dados do combobox do jogador2
     */
    private void atualizaComboboxJogador2() {
        model2 = new DefaultComboBoxModel(carregarCartasMaoJogador2());
        jComboBoxP2.removeAllItems();
        jComboBoxP2.setModel(model2);

    }
    /**
     * Metodo que atualizar o monte de compra
     */

    private void atualizaMonteCompra() {
        Carta primeiraCarta = baralho.getBaralhoCompleto().get(0);
        String monteCompra = primeiraCarta.getNumero() + " " + primeiraCarta.getnaipe();
        jTextFieldMonteCompra.setText(monteCompra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButtonCartaP2 = new javax.swing.JButton();
        jButtonCartaP1 = new javax.swing.JButton();
        jButtonComprarP2 = new javax.swing.JButton();
        jButtonComprarP1 = new javax.swing.JButton();
        jLabelNomeP2 = new javax.swing.JLabel();
        jLabelNomeP1 = new javax.swing.JLabel();
        jTextFieldMonteCompra = new javax.swing.JTextField();
        jComboBoxP2 = new javax.swing.JComboBox();
        jComboBoxP1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCartaNaMesaP1 = new javax.swing.JTextField();
        jTextFieldCartaNaMesaP2 = new javax.swing.JTextField();
        jButtonIniciarJogo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNomeP1 = new javax.swing.JTextField();
        jTextFieldNomeP2 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo de Burro");
        setResizable(false);

        jButtonCartaP2.setText("Jogar Carta");
        jButtonCartaP2.setEnabled(false);
        jButtonCartaP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCartaP2ActionPerformed(evt);
            }
        });

        jButtonCartaP1.setText("Jogar Carta");
        jButtonCartaP1.setEnabled(false);
        jButtonCartaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCartaP1ActionPerformed(evt);
            }
        });

        jButtonComprarP2.setText("Comprar");
        jButtonComprarP2.setEnabled(false);
        jButtonComprarP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarP2ActionPerformed(evt);
            }
        });

        jButtonComprarP1.setText("Comprar");
        jButtonComprarP1.setEnabled(false);
        jButtonComprarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarP1ActionPerformed(evt);
            }
        });

        jLabelNomeP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeP2.setText("Jogador 2");

        jLabelNomeP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeP1.setText("Jogador 1");

        jTextFieldMonteCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMonteCompra.setText("Monte de Compra");
        jTextFieldMonteCompra.setToolTipText("Monte de Compra");
        jTextFieldMonteCompra.setEnabled(false);
        jTextFieldMonteCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonteCompraActionPerformed(evt);
            }
        });

        jComboBoxP2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxP2.setEnabled(false);
        jComboBoxP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxP2ActionPerformed(evt);
            }
        });

        jComboBoxP1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxP1.setEnabled(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cartas Jogador 2");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cartas Jogador 1");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cartas na Mesa");

        jTextFieldCartaNaMesaP1.setEditable(false);
        jTextFieldCartaNaMesaP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCartaNaMesaP1.setText("Carta P1");
        jTextFieldCartaNaMesaP1.setToolTipText("Carta Jogada pelo Jogador 1");
        jTextFieldCartaNaMesaP1.setName(""); // NOI18N
        jTextFieldCartaNaMesaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCartaNaMesaP1ActionPerformed(evt);
            }
        });

        jTextFieldCartaNaMesaP2.setEditable(false);
        jTextFieldCartaNaMesaP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCartaNaMesaP2.setText("Carta P2");
        jTextFieldCartaNaMesaP2.setToolTipText("Carta Jogada pelo Jogador 2");

        jButtonIniciarJogo.setText("Iniciar Novo Jogo");
        jButtonIniciarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarJogoActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome Jogador 1");

        jLabel8.setText("Nome Jogador 2");

        jTextFieldNomeP1.setText("Jogador 1");

        jTextFieldNomeP2.setText("Jogador 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNomeP1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNomeP2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(jButtonIniciarJogo)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelNomeP1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonCartaP1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jButtonComprarP1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jComboBoxP1, 0, 100, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldCartaNaMesaP1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCartaNaMesaP2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldMonteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonComprarP2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jLabelNomeP2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBoxP2, 0, 100, Short.MAX_VALUE)
                        .addComponent(jButtonCartaP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(24, 24, 24)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldNomeP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldNomeP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonIniciarJogo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeP2)
                    .addComponent(jLabelNomeP1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jComboBoxP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCartaP2)
                    .addComponent(jButtonCartaP1)
                    .addComponent(jTextFieldCartaNaMesaP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCartaNaMesaP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonComprarP2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonComprarP1)
                        .addComponent(jTextFieldMonteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxP2ActionPerformed
    /**
     * Metodo responsavel por fazer o jogador 2 jogar uma carta na mesa
     * @param evt
     */
    private void jButtonCartaP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCartaP2ActionPerformed
        String x = (String) jComboBoxP2.getSelectedItem();
        String arrayCarta[] = x.split(" ");
        Carta carta1 = new Carta(arrayCarta[1], arrayCarta[0]);
        //carta jogada pelo jogador 2
        String x2 = (String) jTextFieldCartaNaMesaP1.getText();
        String arrayCarta2[] = x2.split(" ");
        Carta carta2 = new Carta(arrayCarta2[1], arrayCarta2[0]);

        if (jogador2.getNumCartasMao() == 0) {
            JOptionPane.showMessageDialog(rootPane, jogo.verificaVencedor(jogador1, jogador2) + " Você Ganhou!");
        } else if (jogo.mesmoNaipe(carta1, carta2) || jogo.mesmoNumero(carta1, carta2)) {

            jTextFieldCartaNaMesaP2.setText(x);
            jogador2.jogarCarta(carta1);
            this.atualizaComboboxJogador2();
            jButtonCartaP1.setEnabled(true);
            jButtonComprarP1.setEnabled(true);
            jButtonCartaP2.setEnabled(false);
            jButtonComprarP2.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Voce precisa jogar um: "+carta2.getNumero()+" ou uma carta de: "+carta2.getnaipe());
        }
    }//GEN-LAST:event_jButtonCartaP2ActionPerformed

    private void jTextFieldCartaNaMesaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCartaNaMesaP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCartaNaMesaP1ActionPerformed
    /**
     * Metodo responsavel por fazer o jogador 2 comprar uma carta
     * @param evt
     */
    private void jButtonComprarP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarP2ActionPerformed
        if (jogador2.comprarCarta(baralho)) {
            this.atualizaComboboxJogador2();
            this.atualizaMonteCompra();
        } else {
            JOptionPane.showMessageDialog(rootPane, jogo.verificaVencedor(jogador1, jogador2) + " Você Ganhou!");
            jButtonComprarP2.setEnabled(false);
            jButtonComprarP1.setEnabled(false);
            jButtonCartaP1.setEnabled(false);
            jButtonCartaP1.setEnabled(false);
            jButtonCartaP2.setEnabled(false);
            
        }

    }//GEN-LAST:event_jButtonComprarP2ActionPerformed

    private void jTextFieldMonteCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonteCompraActionPerformed
    }//GEN-LAST:event_jTextFieldMonteCompraActionPerformed
    /**
     * Metodo responsavel por fazer o jogador 1 comprar uma carta da mesa
     * @param evt
     */
    private void jButtonComprarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarP1ActionPerformed
        if (jogador1.comprarCarta(baralho)) {
            this.atualizaComboboxJogador1();
            this.atualizaMonteCompra();
        } else {
            JOptionPane.showMessageDialog(rootPane, jogo.verificaVencedor(jogador1, jogador2) + " Você Ganhou!");
            jButtonComprarP2.setEnabled(false);
            jButtonComprarP1.setEnabled(false);
            jButtonCartaP1.setEnabled(false);
            jButtonCartaP1.setEnabled(false);
            jButtonCartaP2.setEnabled(false);
        }


    }//GEN-LAST:event_jButtonComprarP1ActionPerformed
    /**
     * Metodo responsavem por fazer o jogador 1 jogar uma carta
     * @param evt
     */
    private void jButtonCartaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCartaP1ActionPerformed
        //carta a ser jogada pelo jogador 1
        String x = (String) jComboBoxP1.getSelectedItem();
        String arrayCarta[] = x.split(" ");
        Carta carta1 = new Carta(arrayCarta[1], arrayCarta[0]);
        //carta jogada pelo jogador 2
        String x2 = (String) jTextFieldCartaNaMesaP2.getText();
        String arrayCarta2[] = x2.split(" ");
        Carta carta2 = new Carta(arrayCarta2[1], arrayCarta2[0]);
        if (jTextFieldCartaNaMesaP2.getText().equals("Carta P2")) {
            jTextFieldCartaNaMesaP1.setText(x);
            jogador1.jogarCarta(carta1);
            this.atualizaComboboxJogador1();
            jButtonCartaP1.setEnabled(false);
            jButtonComprarP1.setEnabled(false);
            jButtonCartaP2.setEnabled(true);
            jButtonComprarP2.setEnabled(true);
        } //verificação se o jogador 1 ainda possui cartas para jogar
        else if (jogador1.getNumCartasMao() == 0) {
            JOptionPane.showMessageDialog(rootPane, jogo.verificaVencedor(jogador1, jogador2) + "Você Ganhou!");
        } // verificação se a carta eh do mesmo naipe ou do mesmo numero
        else if (jogo.mesmoNaipe(carta1, carta2) || jogo.mesmoNumero(carta1, carta2)) {

            jTextFieldCartaNaMesaP1.setText(x);
            jogador1.jogarCarta(carta1);
            this.atualizaComboboxJogador1();
            jButtonCartaP1.setEnabled(false);
            jButtonComprarP1.setEnabled(false);
            jButtonCartaP2.setEnabled(true);
            jButtonComprarP2.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Voce precisa jogar um: "+carta2.getNumero()+" ou uma carta de: "+carta2.getnaipe());
        }
    }//GEN-LAST:event_jButtonCartaP1ActionPerformed

    /**
     * Metodo que inicia o jogo
     * @param evt
     */
    private void jButtonIniciarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarJogoActionPerformed


        baralho = new Baralho();
        baralho.embaralhar();
        jogador1 = new Jogador(baralho);
        jogador2 = new Jogador(baralho);
        jogo = new JogoDeBurro(jogador1, jogador2, baralho);
        model1 = new DefaultComboBoxModel(carregarCartasMaoJogador1());
        model2 = new DefaultComboBoxModel(carregarCartasMaoJogador2());

        jogador1.setNome(jTextFieldNomeP1.getText());
        jogador2.setNome(jTextFieldNomeP2.getText());
        jLabelNomeP1.setText(jTextFieldNomeP1.getText());
        jLabelNomeP2.setText(jTextFieldNomeP2.getText());
        this.atualizaComboboxJogador1();
        this.atualizaComboboxJogador2();
        this.atualizaMonteCompra();
        jComboBoxP1.setEnabled(true);
        jComboBoxP2.setEnabled(true);
        jButtonCartaP1.setEnabled(true);
        jButtonComprarP1.setEnabled(true);

    }//GEN-LAST:event_jButtonIniciarJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoBurro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoBurro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoBurro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoBurro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoBurro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCartaP1;
    private javax.swing.JButton jButtonCartaP2;
    private javax.swing.JButton jButtonComprarP1;
    private javax.swing.JButton jButtonComprarP2;
    private javax.swing.JButton jButtonIniciarJogo;
    private javax.swing.JComboBox jComboBoxP1;
    private javax.swing.JComboBox jComboBoxP2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNomeP1;
    private javax.swing.JLabel jLabelNomeP2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCartaNaMesaP1;
    private javax.swing.JTextField jTextFieldCartaNaMesaP2;
    private javax.swing.JTextField jTextFieldMonteCompra;
    private javax.swing.JTextField jTextFieldNomeP1;
    private javax.swing.JTextField jTextFieldNomeP2;
    // End of variables declaration//GEN-END:variables
}
