/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodeburro;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import pds.Baralho;
import pds.Carta;

/**
 *
 * @author Helison
 */
public class JogoBurro extends javax.swing.JFrame {

    Baralho baralho;
    Jogador jogador1;
    Jogador jogador2;
    JogoDeBurro jogo;
    DefaultComboBoxModel model1;
    DefaultComboBoxModel model2;

    /**
     * Creates new form JogoBurro
     */
    public JogoBurro() {



        initComponents();
        baralho = new Baralho();
        baralho.embaralhar();
        jogador1 = new Jogador(baralho);
        jogador2 = new Jogador(baralho);
        jogo = new JogoDeBurro(jogador1, jogador2, baralho);
        model1 = new DefaultComboBoxModel(carregarCartasMaoJogador1());
        model2 = new DefaultComboBoxModel(carregarCartasMaoJogador2());

        this.atualizaComboboxJogador1();
        this.atualizaComboboxJogador2();
        this.atualizaMonteCompra();
    }

    private String[] carregarCartasMaoJogador1() {
        String[] maoJogador1 = new String[jogador1.maoJogador.size()];
        for (int i = 0; i < jogador1.maoJogador.size(); i++) {
            String concat = jogador1.maoJogador.get(i).getNumero() + " " + jogador1.maoJogador.get(i).getnaipe();
            maoJogador1[i] = concat;
        }
        return maoJogador1;

    }

    private String[] carregarCartasMaoJogador2() {
        String[] maoJogador1 = new String[jogador2.maoJogador.size()];
        for (int i = 0; i < jogador2.maoJogador.size(); i++) {
            String concat = jogador2.maoJogador.get(i).getNumero() + " " + jogador2.maoJogador.get(i).getnaipe();
            maoJogador1[i] = concat;
        }
        return maoJogador1;

    }

    private void atualizaComboboxJogador1() {
        model1 = new DefaultComboBoxModel(carregarCartasMaoJogador1());
        jComboBoxP1.removeAllItems();
        jComboBoxP1.setModel(model1);
        //jComboBoxP2.setModel(new javax.swing.DefaultComboBoxModel(this.carregarCartasMaoJogador1()));
    }

    private void atualizaComboboxJogador2() {
        model2 = new DefaultComboBoxModel(carregarCartasMaoJogador2());
        jComboBoxP2.removeAllItems();
        jComboBoxP2.setModel(model2);

    }

    private void atualizaMonteCompra() {
        Carta primeiraCarta = baralho.getBaralhoCompleto().get(0);
        String monteCompra = primeiraCarta.getNumero() + " " + primeiraCarta.getnaipe();
        jTextFieldMonteCompra.setText(monteCompra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButtonCartaP2 = new javax.swing.JButton();
        jButtonCartaP1 = new javax.swing.JButton();
        jButtonComprarP2 = new javax.swing.JButton();
        jButtonComprarP1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMonteCompra = new javax.swing.JTextField();
        jComboBoxP2 = new javax.swing.JComboBox();
        jComboBoxP1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCartaNaMesaP1 = new javax.swing.JTextField();
        jTextFieldCartaNaMesaP2 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCartaP2.setText("Jogar Carta");
        jButtonCartaP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCartaP2ActionPerformed(evt);
            }
        });

        jButtonCartaP1.setText("Jogar Carta");
        jButtonCartaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCartaP1ActionPerformed(evt);
            }
        });

        jButtonComprarP2.setText("Comprar");
        jButtonComprarP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarP2ActionPerformed(evt);
            }
        });

        jButtonComprarP1.setText("Comprar");
        jButtonComprarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarP1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jogador 2");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jogador 1");

        jTextFieldMonteCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMonteCompra.setText("Monte de Compra");
        jTextFieldMonteCompra.setToolTipText("Monte de Compra");
        jTextFieldMonteCompra.setEnabled(false);
        jTextFieldMonteCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonteCompraActionPerformed(evt);
            }
        });

        jComboBoxP2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxP2ActionPerformed(evt);
            }
        });

        jComboBoxP1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cartas Jogador 2");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cartas Jogador 1");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cartas na Mesa");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Monte de Compra");

        jTextFieldCartaNaMesaP1.setEditable(false);
        jTextFieldCartaNaMesaP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCartaNaMesaP1.setText("Carta P1");
        jTextFieldCartaNaMesaP1.setToolTipText("Carta Jogada pelo Jogador 1");
        jTextFieldCartaNaMesaP1.setName(""); // NOI18N
        jTextFieldCartaNaMesaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCartaNaMesaP1ActionPerformed(evt);
            }
        });

        jTextFieldCartaNaMesaP2.setEditable(false);
        jTextFieldCartaNaMesaP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCartaNaMesaP2.setText("Carta P2");
        jTextFieldCartaNaMesaP2.setToolTipText("Carta Jogada pelo Jogador 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonCartaP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonComprarP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxP1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMonteCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCartaNaMesaP1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldCartaNaMesaP2))))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonComprarP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCartaP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxP2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCartaNaMesaP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCartaP2)
                    .addComponent(jButtonCartaP1)
                    .addComponent(jTextFieldCartaNaMesaP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonComprarP2)
                    .addComponent(jButtonComprarP1))
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMonteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxP2ActionPerformed

    private void jButtonCartaP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCartaP2ActionPerformed

        String x = (String) jComboBoxP2.getSelectedItem();
        String carta[] = x.split(" ");
        Carta c = new Carta(carta[1], carta[0]);
        jTextFieldCartaNaMesaP2.setText(x);
        jogador2.jogarCarta(c);
        this.atualizaComboboxJogador2();
    }//GEN-LAST:event_jButtonCartaP2ActionPerformed

    private void jTextFieldCartaNaMesaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCartaNaMesaP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCartaNaMesaP1ActionPerformed

    private void jButtonComprarP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarP2ActionPerformed
        jogador2.comprarCarta(baralho);
        this.atualizaComboboxJogador2();
        this.atualizaMonteCompra();

    }//GEN-LAST:event_jButtonComprarP2ActionPerformed

    private void jTextFieldMonteCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonteCompraActionPerformed
    }//GEN-LAST:event_jTextFieldMonteCompraActionPerformed

    private void jButtonComprarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarP1ActionPerformed
        jogador1.comprarCarta(baralho);
        this.atualizaComboboxJogador1();
        this.atualizaMonteCompra();

    }//GEN-LAST:event_jButtonComprarP1ActionPerformed

    private void jButtonCartaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCartaP1ActionPerformed
        String x = (String) jComboBoxP1.getSelectedItem();
        String carta[] = x.split(" ");
        Carta c = new Carta(carta[1], carta[0]);
        jTextFieldCartaNaMesaP1.setText(x);
        jogador1.jogarCarta(c);
        this.atualizaComboboxJogador1();
    }//GEN-LAST:event_jButtonCartaP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoBurro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoBurro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoBurro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoBurro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoBurro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCartaP1;
    private javax.swing.JButton jButtonCartaP2;
    private javax.swing.JButton jButtonComprarP1;
    private javax.swing.JButton jButtonComprarP2;
    private javax.swing.JComboBox jComboBoxP1;
    private javax.swing.JComboBox jComboBoxP2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCartaNaMesaP1;
    private javax.swing.JTextField jTextFieldCartaNaMesaP2;
    private javax.swing.JTextField jTextFieldMonteCompra;
    // End of variables declaration//GEN-END:variables
}
